---
# mesos-master-local
mesosphere_major: 7
mesosphere_minor: 3
quorum: 1
cluster_name: "test"
ip_address: 192.168.56.102
zookeeper_id: 1
zk_nodes: 192.168.56.102:2181
zk_server_nodes: | 
  server.1=192.168.56.102:2888:3888
