---
# zookeeper/tasks/main.yml
- name: zookeeper container
  tags: zookeeper
  docker:
    name: zookeeper
    docker_api_version: '{{ docker_api_version }}'
    image: '{{ external_docker_registry }}mesoscloud/zookeeper:3.4.6-centos-7'
    state: restarted
    restart_policy: always
    net: host
    env:
      MYID: 1
      SERVERS: '{{ zookeeper_servers }}'
  become: true
