---
# init-examples/handlers/main.yml
- name: push landsat-parse
  command: sh -c 'docker tag -f landsat-parse_1.0:{{ example_image_tag }} {{ docker_registry }}landsat-parse_1.0:{{ example_image_tag }}; docker push {{ docker_registry }}landsat-parse_1.0:{{ example_image_tag }}'
  become: true

- name: push landsat-ndwi
  command: sh -c 'docker tag -f landsat-ndwi_1.0:{{ example_image_tag }} {{ docker_registry }}landsat-ndwi_1.0:{{ example_image_tag }}; docker push {{ docker_registry }}landsat-ndwi_1.0:{{ example_image_tag }}'
  become: true

- name: push landsat-tiles
  command: sh -c 'docker tag -f landsat-tiles_1.0:{{ example_image_tag }} {{ docker_registry }}landsat-tiles_1.0:{{ example_image_tag }}; docker push {{ docker_registry }}landsat-tiles_1.0:{{ example_image_tag }}'
  become: true

- name: push pca
  command: sh -c 'docker tag -f pca_1.0:{{ example_image_tag }} {{ docker_registry }}pca_1.0:{{ example_image_tag }}; docker push {{ docker_registry }}pca_1.0:{{ example_image_tag }}'
  become: true

- name: push vash
  command: sh -c 'docker tag -f vash_1.0:{{ example_image_tag }} {{ docker_registry }}vash_1.0:{{ example_image_tag }}; docker push {{ docker_registry }}vash_1.0:{{ example_image_tag }}'
  become: true

