---
# install-scale/tasks/main.yml
- name: Install unzip
  tags: [ install-scale ]
  yum: name=unzip
  become: true

- name: Install postgresql client and libs
  tags: [ install-scale ]
  yum: name=postgresql
  become: true

- name: Install gdal python
  tags: [ install-scale ]
  yum: name=gdal-python
  become: true

- name: Install psycopg2
  tags: [ install-scale ]
  yum: name=python-psycopg2
  become: true

- name: Install geos
  tags: [ install-scale ]
  yum: name=geos
  become: true

- name: Install subversion libs
  tags: [ install-scale ]
  yum: name=subversion-libs
  become: true

- name: Install protobuf
  tags: [ install-scale ]
  yum: name=protobuf
  become: true

- name: Install python-devel
  tags: build-scale
  yum: name=python-devel
  become: true

- name: Install npm
  tags: [ install-scale ]
  yum: name=npm
  become: true

- name: Install node-gyp
  tags: [ install-scale ]
  yum: name=node-gyp
  become: true

- name: Install gulp
  tags: [ install-scale ]
  npm: name=gulp global=true
  become: true

- name: Install python google-apputils
  tags: [ install-scale ]
  pip: name=google-apputils


