---
# mesos-master/tasks/main.yml
- name: mesos master container
  tags: mesos-master
  docker:
    name: mesos-master
    docker_api_version: '{{ docker_api_version }}'
    image: '{{ external_docker_registry }}mesoscloud/mesos-master:0.24.1'
    state: reloaded
    restart_policy: always
    net: host
    hostname: '{{ inventory_hostname }}'
    env:
      MESOS_QUORUM: '{{ mesos_quorum }}'
      MESOS_ZK: '{{ mesos_zk }}'
      MESOS_IP: '{{ mesos_master_ip }}'
      MESOS_LOG_DIR: '/var/log/mesos'
      MESOS_CLUSTER: 'scale'
      MESOS_NO_HOSTNAME_LOOKUP: 'true'
  become: true
