---
# postgis/tasks/main.yml
- name: PostGIS database
  tags: postgis
  docker:
    name: postgis
    docker_api_version: '{{ docker_api_version }}'
    image: '{{ external_docker_registry }}mdillon/postgis'
    state: started
    restart_policy: always
    ports:
      - "5432:5432"
    env:
      POSTGRES_PASSWORD: '{{ db_password }}'
  become: true
