---
- name: Install postgres and postgis
  tags: init-database
  yum: name={{item}}
  become: true
  with_items:
  - postgresql94
  - postgresql94-debuginfo
  - postgresql94-server
  - postgresql94-devel
  - postgis2_94
  - postgis2_94-devel

- name: Install psycopg2
  tags: init-database
  yum: name=python-psycopg2
  become: true

- name: Initialize Database
  tags: init-database
  command: /usr/pgsql-9.4/bin/postgresql94-setup initdb creates=/var/lib/pgsql/9.4/data/pg_hba.conf
  become: true

- name: Update pg_hba.conf
  tags: init-database
  template: src=pg_hba.conf.j2 dest='/var/lib/pgsql/9.4/data/pg_hba.conf'
  become: true

- name: Update postgresql.conf
  tags: init-database
  template: src=postgresql.conf.j2 dest='/var/lib/pgsql/9.4/data/postgresql.conf'
  become: true

- name: Start database server
  tags: init-database
  service: name=postgresql-9.4 state=restarted
  become: true

- name: Change postgres user default password
  tags: init-database
  postgresql_user: name=postgres password=postgres_scale
  become: true

- name: Create scale database user
  tags: init-database
  postgresql_user: name=scale password=scale role_attr_flags=SUPERUSER
  become: true

- name: Create scale database
  tags: init-database
  postgresql_db: name=scale owner=scale
  become: true

- name: Add postgis extension
  tags: init-database
  postgresql_ext: name=postgis db=scale
  become: true

- name: Add postgis_topology extension
  tags: init-database
  postgresql_ext: name=postgis_topology db=scale
  become: true

- name: Start database server
  tags: init-database
  service: name=postgresql-9.4 state=restarted
  become: true
