---
# install-scale/tasks/main.yml
- name: Disable firewall
  tags: [ install-scale ]
  service: name=firewalld state=stopped enabled=false
  become: true

- name: Install python-pip
  tags: [ install-scale ]
  yum: name=python-pip
  become: true
  
- name: Install docker-py
  tags: [ install-scale ]
  pip: name=docker-py version=1.5.0
  become: true

- name: Install docker
  tags: [ install-scale ]
  yum: name=docker-engine-1.9.1
  become: true

- name: docker service
  tags: [ install-scale ]
  service: name=docker state=started enabled=true
  become: true

- name: create docker service folder
  tags: [ install-scale ]
  file: path=/etc/systemd/system/docker.service.d state=directory
  become: true

- name: install docker config file
  tags: [ install-scale ]
  template: src=docker.conf.j2 dest=/etc/systemd/system/docker.service.d/docker.conf
  become: true

- name: systemctl daemon reload
  tags: [ install-scale ]
  command: systemctl daemon-reload
  become: true

- name: restart docker service
  tags: [ install-scale ]
  service: name=docker state=restarted
  become: true

- name: Install rsync
  tags: [ install-scale ]
  yum: name=rsync
  become: true

- name: Install unzip
  tags: [ install-scale ]
  yum: name=unzip
  become: true

- name: Install postgresql client and libs
  tags: [ install-scale ]
  yum: name=postgresql
  become: true

- name: Install gdal python
  tags: [ install-scale ]
  yum: name=gdal-python
  become: true

- name: Install psycopg2
  tags: [ install-scale ]
  yum: name=python-psycopg2
  become: true

- name: Install geos
  tags: [ install-scale ]
  yum: name=geos
  become: true

- name: Install subversion libs
  tags: [ install-scale ]
  yum: name=subversion-libs
  become: true

- name: Install protobuf
  tags: [ install-scale ]
  yum: name=protobuf
  become: true

- name: Install python-devel
  tags: build-scale
  yum: name=python-devel
  become: true

- name: Install npm
  tags: [ install-scale ]
  yum: name=npm
  become: true

- name: Install node-gyp
  tags: [ install-scale ]
  yum: name=node-gyp
  become: true

- name: Install global npm modules
  tags: [ install-scale ]
  unarchive: src=usr_lib_node_modules.tar.gz dest=/
  become: true

- name: Create link to gulp
  tags: [ install-scale ]
  file: src=/usr/lib/node_modules/gulp/bin/gulp.js dest=/usr/bin/gulp state=link
  become: true

- name: Install python google-apputils
  tags: [ install-scale ]
  pip: name=google-apputils
  become: true


