---
# db-init/tasks/main.yml
- name: Wait for the postgis database to initialize itself
  tags: db-init
  wait_for: port=5432 host='{{ db_host }}' delay=10

- name: Install psycopg2
  tags: db-init
  yum: name=python-psycopg2
  become: true

- name: Initialize postgres database
  tags: db-init
  postgresql_db: name='{{ db_name }}'
                 template=template_postgis
                 login_host='{{ db_host }}'
                 login_user='{{ db_username }}'
                 login_password='{{ db_password }}'