---
# vagrant.yml
# site file for vagrant cluster
- hosts: db
  roles:
    - postgis
    - db-init

- hosts: scale-framework
  roles:
#    - dns-server
    - docker-registry
#    - nfs-server

#- hosts: all
#  tasks:
#    - name: Setup resolv.conf
#      command: sh -c 'echo "nameserver 10.4.4.10" > /etc/resolv.conf'
#      become: true

- hosts: scale-framework
  roles:
    - build-scale

- hosts: scale-framework
  roles:
    - load-initial-data
    - init-examples

- include: mesos.yml
- include: scale.yml
