---
# init-environment/tasks/common.yml

- name: clean all repos
  tags: [ init-environment ] 
  command: yum clean all
  become: true

- name: install pip
  tags: [ init-environment ] 
  yum: name=python-pip
  become: true

- name: install ansible hosts file
  tags: [ init-environment ]
  copy: src=ansible_hosts dest=/etc/ansible/hosts
  become: true

- name: disable firewalld
  tags: [ init-environment ]
  service: firewalld state=stopped enabled=false
  become: true

- name: disable selinux
  tags: [ init-environment ]
  selinux: state=disabled
  become: true

- name: create main group
  tags: [ init-environment ]
  group: name={{ mesos_group }}
  become: true

- name: create main user
  tags: [ init-environment ]
  user: name={{ mesos_user }} group={{ mesos_group }}
  become: true

- name: install httpd server
  tags: [ init-environment ]
  yum: name=httpd
  become: true
  when: connection_state != "internet"
  
- name: configure httpd server
  tags: [ init-environment ]
  template: src=httpd.conf.j2 dest=/etc/httpd/conf/httpd.conf
  become: true
  when: connection_state != "internet"

- name: start httpd server
  tags: [ init-environment ]
  service: name=httpd state=started enabled=yes
  become: true  
  when: connection_state != "internet"
  
- name: set permission on data dir
  tags: [ init-environment ]
  file: path={{ httpd_data_dir }} mode=0755
  become: true
  
- name: set permission on rpm dir
  tags: [ init-environment ]
  file: path={{ httpd_data_dir }}{{ httpd_repo_dir }} mode=0755 recurse=yes
  become: true
  when: connection_state != "internet"
  
- name: set permission on pip dir
  tags: [ init-environment ]
  file: path={{ httpd_data_dir }}{{ httpd_pip_dir }} mode=0755 recurse=yes
  become: true
  when: connection_state != "internet"

- name: restart httpd server
  tags: [ init-environment ]
  service: name=httpd state=restarted
  become: true  
  when: connection_state != "internet"

- name: configure pip
  tags: [ init-environment ] 
  template: src=pip.conf dest=/etc/pip.conf
  become: true
  when: connection_state != "internet"
    
- name: configure easy_install
  tags: [ init-environment ] 
  template: src=pydistutils.cfg dest=~/.pydistutils.cfg
  when: connection_state != "internet"

- name: update ansible
  tags: [ init-environment ] 
  pip: name=ansible state=latest
  become: true

- name: refresh hosts file
  tags: [ init-environment ]
  meta: refresh_inventory
  become: true

- name: create ~/.ssh dir
  tags: [ init-environment ]
  file: path=~/.ssh state=directory
  
- name: add all ips to known_hosts
  tags: [ init-environment ]
  shell: ssh-keyscan -H {{ item }} >> ~/.ssh/known_hosts
  with_items: "{{ groups['all'] }}"

- name: create data conf folder
  tags: [ init-environment ]
  file: path="{{ httpd_data_dir}}/conf" state=directory

- name: add repo conf file to the /data/conf folder
  tags: [ init-environment ]
  template: src=local.repo.j2 dest="{{ httpd_data_dir}}/conf/local.repo"
  
- name: add repo conf file to the scale docker folder
  tags: [ init-environment ]
  template: src=local.repo.docker.j2 dest="{{ playbook_dir }}/../dockerfiles/framework/scale/local.repo"
  
- name: add pip conf file to the /data/conf folder
  tags: [ init-environment ]
  template: src=pip.conf.j2 dest="{{ httpd_data_dir}}/conf/pip.conf"
  
- name: add pip conf file to the scale docker folder
  tags: [ init-environment ]
  template: src=pip.conf.docker.j2 dest="{{ playbook_dir }}/../dockerfiles/framework/scale/pip.conf"
  
- name: add easy_install conf file to the /data/conf folder
  tags: [ init-environment ]
  template: src=pydistutils.cfg.j2 dest="{{ httpd_data_dir}}/conf/pydistutils.cfg"

- name: add easy_install conf file to the scale docker folder
  tags: [ init-environment ]
  template: src=pydistutils.cfg.docker.j2 dest="{{ playbook_dir }}/../dockerfiles/framework/scale/pydistutils.cfg"

