---
# init-environment/tasks/common.yml

- name: clean all repos
  tags: [ init-environment ] 
  command: yum clean all
  become: true

- name: install pip
  tags: [ init-environment ] 
  yum: name=python-pip
  become: true

- name: install ansible hosts file
  tags: [ init-environment ]
  copy: src=ansible_hosts dest=/etc/ansible/hosts
  become: true

- name: disable firewalld
  tags: [ init-environment ]
  service: name=firewalld state=stopped enabled=false
  become: true

- name: disable selinux
  tags: [ init-environment ]
  selinux: state=disabled
  become: true

- name: create main group
  tags: [ init-environment ]
  group: name={{ mesos_group }}
  become: true

- name: create main user
  tags: [ init-environment ]
  user: name={{ mesos_user }} group={{ mesos_group }}
  become: true

- name: install httpd server
  tags: [ init-environment ]
  yum: name=httpd
  become: true
  when: connection_state != "internet"
  
- name: configure httpd server
  tags: [ init-environment ]
  template: src=httpd.conf.j2 dest=/etc/httpd/conf/httpd.conf
  become: true
  when: connection_state != "internet"

- name: start httpd server
  tags: [ init-environment ]
  service: name=httpd state=started enabled=yes
  become: true  
  when: connection_state != "internet"
  
- name: set permission on data dir
  tags: [ init-environment ]
  file: path={{ httpd_data_dir }} mode=0755
  become: true
  
- name: set permission on rpm dir
  tags: [ init-environment ]
  file: path={{ httpd_data_dir }}/{{ httpd_repo_dir }} mode=0755 recurse=yes state=directory
  become: true
  when: connection_state != "internet"
  
- name: set permission on pip dir
  tags: [ init-environment ]
  file: path={{ httpd_data_dir }}/{{ httpd_pip_dir }} mode=0755 recurse=yes state=directory
  become: true
  when: connection_state != "internet"

- name: restart httpd server
  tags: [ init-environment ]
  service: name=httpd state=restarted
  become: true  
  when: connection_state != "internet"

- name: configure local repo
  tags: [ init-environment ] 
  template: src=local.repo.j2 dest=/etc/yum.repos.d/local.repo
  become: true
  when: connection_state != "internet"

- name: delete temp offline repo
  tags: [ init-environment ] 
  file: path=/etc/yum.repos.d/temp.repo state=absent
  become: true
  when: connection_state == "offline"

- name: clean all repos
  tags: [ init-environment ] 
  command: yum clean all
  become: true
  when: connection_state != "internet"

- name: configure pip
  tags: [ init-environment ] 
  template: src=pip.conf.j2 dest=/etc/pip.conf
  become: true
  when: connection_state != "internet"
    
- name: configure easy_install
  tags: [ init-environment ] 
  template: src=pydistutils.cfg.j2 dest=~/.pydistutils.cfg
  when: connection_state != "internet"

- name: create ~/.ssh dir
  tags: [ init-environment ]
  file: path=~/.ssh state=directory
  
- name: add all ips to known_hosts
  tags: [ init-environment, known-hosts ]
  shell: ssh-keyscan -H {{ item }} >> ~/.ssh/known_hosts
  with_items: "{{ groups['all'] }}"

- name: create conf dir
  tags: [ init-environment ]
  file: path="{{ httpd_data_dir }}/conf/" state=directory
  
- name: copy repos to the conf folder
  tags: [ init-environment ]
  copy: src="{{ item }}" dest="{{ httpd_data_dir }}/conf/"
  with_fileglob:
    - /etc/yum.repos.d/*.repo
  
- name: copy repo conf file to the scale docker folder
  tags: [ init-environment ]
  copy: src="{{ item }}" dest="{{ playbook_dir }}/../dockerfiles/framework/scale/"
  with_fileglob:
    - /etc/yum.repos.d/*.repo
  
- name: copy pip conf file to the scale docker folder
  tags: [ init-environment ]
  copy: src=/etc/pip.conf dest="{{ playbook_dir }}/../dockerfiles/framework/scale/"
  when: connection_state != "internet"
  
- name: copy easy_install conf file to the scale docker folder
  tags: [ init-environment ]
  copy: src=~/.pydistutils.cfg dest="{{ playbook_dir }}/../dockerfiles/framework/scale/"
  when: connection_state != "internet"

- name: update ansible
  tags: [ init-environment ] 
  pip: name=ansible state=latest
  become: true


