---
# init-environment/tasks/main.yml

- include: offline.yml
  when: connection_state == "offline"

- include: online.yml
  when: connection_state == "online"

- include: internet.yml
  when: connection_state == "internet"

- include: common.yml
