---
# init-environment/tasks/main.yml

- name: install createrepo
  tags: [ init-environment ] 
  yum: name={{item}}
  become: true
  with_items:
  - /data/scale_rpm/libxml2-2.9.1-6.el7_2.2.x86_64.rpm
  - /data/scale_rpm/python-deltarpm-3.6-3.el7.x86_64.rpm
  - /data/scale_rpm/libxml2-python-2.9.1-6.el7_2.2.x86_64.rpm
  - /data/scale_rpm/deltarpm-3.6-3.el7.x86_64.rpm
  - /data/scale_rpm/createrepo-0.9.9-25.el7_2.noarch.rpm

- name: create repo
  tags: [ init-environment ] 
  command: createrepo /data/repo
  become: true

- name: remove existing repos
  tags: [ init-environment ] 
  shell: rm -f /etc/yum.repos.d/*.repo
  become: true

- name: add new repo
  tags: [ init-environment ] 
  copy: src=local.repo dest=/etc/yum.repos.d/local.repo
  become: true

- name: clean all repos
  tags: [ init-environment ] 
  command: yum clean all
  become: true

- name: create pip conf dir
  tags: [ init-environment ]
  file: path=~/.pip state=directory

- name: configure pip
  tags: [ init-environment ] 
  copy: src=pip.conf dest=~/.pip/pip.conf
  
- name: configure easy_install
  tags: [ init-environment ] 
  copy: src=pydistutils.cfg dest=~/.pydistutils.cfg
  
- name: install ansible hosts file
  tags: [ init-environment ]
  copy: src=ansible_hosts dest=/etc/ansible/hosts
  become: true
  
- name: add all ips to known_hosts
  tags: [ init-environment ]
  shell: ssh-keyscan -H {{ item }} >> ~/.ssh/known_hosts
  with_items: groups['all']

- name: install httpd server
  tags: [ init-environment ]
  yum: name=httpd
  become: true
  
- name: configure httpd server
  tags: [ init-environment ]
  template: src=httpd.conf.j2 dest=/etc/httpd/conf/httpd.conf
  become: true

- name: start httpd server
  tags: [ init-environment ]
  service: name=httpd state=started enabled=yes
  become: true  
  
- name: set permission on data dir
  tags: [ init-environment ]
  file: path={{ httpd_data_dir }} mode=0755
  become: true
  
- name: set permission on rpm dir
  tags: [ init-environment ]
  file: path={{ httpd_rpm_dir }} mode=0755 recurse=yes
  become: true
  
- name: set permission on pip dir
  tags: [ init-environment ]
  file: path={{ httpd_pip_dir }} mode=0755 recurse=yes
  become: true
  
- name: update selinux state on data dir
  tags: [ init-environment ]
  command: semanage fcontext -a -t httpd_sys_content_t "{{ httpd_data_dir }}(/.*)?"
  become: true
  
- name: restorecon on data dir
  tags: [ init-environment ]
  command: restorecon -R {{ httpd_data_dir }}
  become: true
  
- name: restart httpd server
  tags: [ init-environment ]
  service: name=httpd state=restarted
  become: true  
  
- name: create data conf folder
  tags: [ init-environment ]
  file: path="{{ httpd_data_dir}}/conf" state=directory

- name: add repo conf file to the /data/conf folder
  tags: [ init-environment ]
  template: src=local.repo.j2 dest="{{ httpd_data_dir}}/conf/local.repo"
  
- name: add pip conf file to the /data/conf folder
  tags: [ init-environment ]
  template: src=pip.conf.j2 dest="{{ httpd_data_dir}}/conf/pip.conf"
  
- name: add easy_install conf file to the /data/conf folder
  tags: [ init-environment ]
  template: src=pydistutils.cfg.j2 dest="{{ httpd_data_dir}}/conf/pydistutils.cfg"

  
  