---
# init-examples/tasks/main.yml
- name: Install initialization script
  tags: init-examples
  copy: src=example_data.py dest=/tmp/example_data.py

- name: Install the countries shapefile
  tags: init-examples
  unarchive: src=TM_WORLD_BORDERS-0.3.zip dest=/tmp

- name: Initialize example database
  tags: init-examples
  command: sh -c "echo \"execfile('/tmp/example_data.py')\" | /scale/scale/manage.py shell"

- name: Build landsat-parse docker image
  tags: init-examples
  docker_image:
    path: "/scale/dockerfiles/examples/landsat-parse"
    name: "landsat-parse_1.0"
    tag: "dev"
    state: build
  become: true
  notify:
    - push landsat-parse

- name: Build landsat-ndwi docker image
  tags: init-examples
  docker_image:
    path: "/scale/dockerfiles/examples/landsat-ndwi"
    name: "landsat-ndwi_1.0"
    tag: "dev"
    state: build
  become: true
  notify:
    - push landsat-ndwi
