---
# db-init-local/tasks/main.yml
- name: Copy postgres rpm
  tags: db-init-local
  copy: src=pgdg-centos94-9.4-2.noarch.rpm dest=/tmp/pgdg-centos94-9.4-2.noarch.rpm

- name: Install postgres repo
  tags: db-init-local
  yum: name=/tmp/pgdg-centos94-9.4-2.noarch.rpm
  become: true

- name: Install postgres and postgis
  tags: db-init-local
  yum: name={{item}}
  become: true
  with_items:
  - postgresql94
  - postgresql94-debuginfo
  - postgresql94-server
  - postgresql94-devel
  - postgis2_94
  - postgis2_94-devel

- name: Initialize Database
  tags: db-init-local
  command: /usr/pgsql-9.4/bin/postgresql94-setup initdb creates=/var/lib/pgsql/9.4/data/pg_hba.conf

- name: Update pg_hba.conf
  tags: db-init-local
  template: src=pg_hba.conf.j2 dest='/var/lib/pgsql/9.4/data/pg_hba.conf'

- name: Update postgresql.conf
  tags: db-init-local
  template: src=postgresql.conf.j2 dest='/var/lib/pgsql/9.4/data/postgresql.conf'

- name: Start database server
  tags: db-init-local
  service: name=postgresql-9.4 state=restarted

- name: Create scale database user
  tags: db-init-local
  postgresql_user: name=scale password=scale role_attr_flags=SUPERUSER

- name: Create scale database
  tags: db-init-local
  postgresql_db: name=scale owner=scale

- name: Add postgis extension
  tags: db-init-local
  postgresql_ext: name=postgis db=scale

- name: Add postgis_topology extension
  tags: db-init-local
  postgresql_ext: name=postgis_topology db=scale

- name: Start database server
  tags: db-init-local
  service: name=postgresql-9.4 state=restarted

