---
# build-scale/tasks/main.yml
- name: Install unzip
  tags: build-scale
  yum: name=unzip
  become: true

- name: Install postgresql client and libs
  tags: build-scale
  yum: name=postgresql
  become: true

- name: Install gdal python
  tags: build-scale
  yum: name=gdal-python
  become: true

- name: Install psycopg2
  tags: build-scale
  yum: name=python-psycopg2
  become: true

- name: Install geos
  tags: build-scale
  yum: name=geos
  become: true

- name: Install subversion libs
  tags: build-scale
  yum: name=subversion-libs
  become: true

- name: Install protobuf
  tags: build-scale
  yum: name=protobuf
  become: true

- name: Install python-devel
  tags: build-scale
  yum: name=python-devel
  become: true

- name: Install npm
  tags: build-scale
  yum: name=npm
  become: true

- name: Install node-gyp
  tags: build-scale
  yum: name=node-gyp
  become: true

- name: Install gulp
  tags: build-scale
  npm: name=gulp global=true
  become: true

- name: Install python google-apputils
  tags: build-scale
  pip: name=google-apputils
  become: true

- name: Install python build libraries
  tags: build-scale
  pip: requirements=/scale/scale/pip/build_linux.txt
  become: true

- name: Install npm ui dependencies
  tags: build-scale
  npm: path=/scale/scale-ui
  become: true

- name: Build ui with gulp
  tags: build-scale
  command: gulp deploy chdir=/scale/scale-ui creates=/scale/scale-ui/deploy/

- name: Create ui target
  tags: build-scale
  file: path=/scale/scale/ui state=directory

- name: Install ui files
  tags: build-scale
  unarchive: copy=no src=$archive dest=/scale/scale/ui
  with_fileglob: "/scale/scale-ui/deplot/scale*.tar.gz"

- name: Install local_settings.py
  tags: build-scale
  template: src=local_settings.py.j2 dest='/scale/scale/scale/local_settings.py'

- name: Create database migrations.
  tags: build-scale
  django_manage: command=makemigrations app_path='{{ django_build_dir }}'

#- name: Create docs
#  tags: build-scale
#  command: make code_docs html chdir=/scale/scale/docs

- name: Collect static files.
  tags: build-scale
  django_manage: command=collectstatic app_path='{{ django_build_dir }}'

- name: Copy built files to the docker directory
  tags: build-scale
  command: cp -R /scale/scale /scale/dockerfiles/framework/scale/

- name: Build scale docker image
  tags: [build-scale, build-scale-docker]
  docker_image:
    path: "/scale/dockerfiles/framework/scale"
    name: "scale"
    tag: "{{ scale_docker_version }}"
    state: build
  become: true
  notify:
    - push scale

- name: Build scale noentry docker image
  tags: [build-scale, build-scale-docker, build-scale-noentry]
  docker_image:
    path: "/scale/dockerfiles/framework/scale-noentry"
    name: "scale-noentry"
    tag: "{{ scale_docker_version }}"
    state: build
  become: true
  notify:
    - push scale-noentry

- name: Build scale-slave docker image
  tags: [build-scale, build-scale-docker]
  docker_image:
    path: "/scale/dockerfiles/framework/scale-slave"
    name: "scale-slave"
    tag: "{{ scale_docker_version }}"
    state: build
  become: true
  notify:
    - push scale-slave

- name: Build scale-web docker image
  tags: [build-scale, build-scale-docker]
  docker_image:
    path: "/scale/dockerfiles/framework/scale-web"
    name: "scale-web"
    tag: "{{ scale_docker_version }}"
    state: build
  become: true
  notify:
    - push scale-web

- name: Build scale-httpd docker image
  tags: [build-scale, build-scale-docker]
  docker_image:
    path: "/scale/dockerfiles/framework/httpd"
    name: "scale-httpd"
    tag: "1"
    state: build
  become: true
  notify:
    - push scale-httpd

- name: Build scale-web-static docker image
  tags: [build-scale, build-scale-docker]
  docker_image:
    path: "/scale/dockerfiles/framework/scale-web-static"
    name: "scale-web-static"
    tag: "{{ scale_docker_version }}"
    state: build
  become: true
  notify:
    - push scale-web-static
