---
# build-scale/tasks/main.yml
- name: Verify scale folder
  tags: [ build-scale, build-scale-sync ]
  stat: path={{ scale_build_root }}
  register: scale_root_folder

- name: Create scale folder
  tags: [ build-scale, build-scale-sync ]
  file: path='{{ scale_build_root }}' state=directory mode=755
  become: true
  when: scale_root_folder.stat.exists == False

- name: Check for ssh keys
  tags: [ build-scale, build-scale-sync ]
  stat: path=~/.ssh/id_rsa
  register: user_ssh_keys

- name: Get the username running the deploy
  tags: [ build-scale, build-scale-sync ]
  local_action: command whoami
  register: username_on_host
  become: no
  
- name: Change scale folder owner
  tags: [ build-scale, build-scale-sync ]
  file: path='{{ scale_build_root }}' state=directory owner={{ username_on_host.stdout }}
  become: true

- name: Create ssh keys
  tags: [ build-scale, build-scale-sync ]
  user: name={{ username_on_host.stdout }} generate_ssh_key=yes ssh_key_file=.ssh/id_rsa
  when: user_ssh_keys.stat.exists == False
  
- name: Add ssh keys
  tags:  [ build-scale, build-scale-sync ]
  authorized_key: user={{ username_on_host.stdout }} key={{ lookup('file', '~/.ssh/id_rsa.pub') }} state=present
  become: true

- name: Install scale
  tags: [ build-scale, build-scale-sync ]
  sudo: no
  synchronize: src="{{ playbook_dir }}/.." dest='{{ scale_build_root }}' delete=yes

- name: Install libpqxx-devel
  tags: [ build-scale, build-scale-minimal ]
  yum: name=libpqxx-devel
  become: true

- name: Install postgresql-devel
  tags: [ build-scale, build-scale-minimal ]
  yum: name=postgresql-devel
  become: true

- name: Install python build libraries
  tags: [ build-scale, build-scale-minimal ]
  pip: requirements='{{ scale_build_root }}/scale/pip/build_linux.txt'
  become: true

- name: Install npm ui dependencies
  tags: [ build-scale, build-scale-minimal ]
  npm: path='{{ scale_build_root }}/scale-ui'

- name: Build ui with gulp
  tags: [ build-scale, build-scale-minimal ]
  command: gulp deploy chdir='{{ scale_build_root }}/scale-ui'

- name: Remove previous build
  tags: build-scale
  file: path='{{ scale_build_root }}/scale/ui' state=absent

- name: Create ui target
  tags: [ build-scale, build-scale-minimal ]
  file: path='{{ scale_build_root }}/scale/ui' state=directory

- name: Install ui files
  tags: [ build-scale, build-scale-minimal ]
  unarchive: copy=no src='{{ item }}' dest='{{ scale_build_root }}/scale/ui'
  with_fileglob: "{{ scale_build_root }}/scale-ui/deploy/scale*.tar.gz"

- name: Install local_settings.py
  tags: [ build-scale, build-scale-minimal ]
  template: src=local_settings.py.j2 dest='{{ scale_build_root }}/scale/scale/local_settings.py'

- name: Create database migrations.
  tags: [ build-scale, build-scale-minimal ]
  django_manage: command=makemigrations app_path='{{ django_build_dir }}'

#- name: Create docs
#  tags: [ build-scale, build-scale-minimal ]
#  command: make code_docs html chdir='{{ scale_build_root }}/scale/docs'

- name: Collect static files.
  tags: [ build-scale, build-scale-minimal ]
  django_manage: command=collectstatic app_path='{{ django_build_dir }}'

- name: Delete built files
  tags: [ build-scale, build-scale-docker, build-scale-minimal ]
  file: path={{ scale_build_root }}/dockerfiles/framework/scale/scale state=absent

- name: Copy built files to the docker directory
  tags: [ build-scale, build-scale-docker, build-scale-minimal ]
  command: "rsync -a {{ scale_build_root }}/scale {{ scale_build_root }}/dockerfiles/framework/scale"

- name: Build scale docker image
  tags: [ build-scale, build-scale-docker ]
  docker_image:
    path: "{{ scale_build_root }}/dockerfiles/framework/scale"
    name: "scale"
    tag: "{{ scale_docker_version }}"
    state: build
    nocache: yes
  become: true
  notify:
    - push scale

- name: Ensure {{ scale_build_root }}/dockerfiles/framework/scale-web/temp/ dir exists
  tags: [ build-scale, build-scale-docker ]
  file: path={{ scale_build_root }}/dockerfiles/framework/scale-web/temp/ state=directory

- name: Copy scale-web Dockerfile
  tags: [ build-scale, build-scale-docker ]
  copy: src=../../../../dockerfiles/framework/scale-web/Dockerfile dest={{ scale_build_root }}/dockerfiles/framework/scale-web/temp/Dockerfile

- name: Replace base image in scale-web Dockerfile
  tags: [ build-scale, build-scale-docker ]
  lineinfile: dest={{ scale_build_root }}/dockerfiles/framework/scale-web/temp/Dockerfile line="FROM scale:{{ scale_docker_version }}" regexp="^FROM .*$"

- name: Build scale-web docker image
  tags: [ build-scale, build-scale-docker ]
  docker_image:
    path: "{{ scale_build_root }}/dockerfiles/framework/scale-web/temp/"
    name: "scale-web"
    tag: "{{ scale_docker_version }}"
    state: build
    nocache: yes
  become: true
  notify:
    - push scale-web

- name: Build scale-httpd docker image
  tags: [build-scale, build-scale-docker]
  docker_image:
    path: "/scale/dockerfiles/framework/httpd"
    name: "scale-httpd"
    tag: "1"
    state: build
    nocache: yes
  become: true
  notify:
    - push scale-httpd

- name: Build scale-web-static docker image
  tags: [ build-scale, build-scale-docker ]
  docker_image:
    path: "{{ scale_build_root }}/dockerfiles/framework/scale-web-static"
    name: "scale-web-static"
    tag: "{{ scale_docker_version }}"
    state: build
    nocache: yes
  become: true
  notify:
    - push scale-web-static
